"use client"; import { useRouter } from "next/navigation";
import { House, PawPrint, PersonSimpleWalk } from "@phosphor-icons/react";
import { FormFooter } from "@/components/ui/FormFooter";
import { FormHeader } from "@/components/ui/FormHeader";
import { useSignupDraft } from "@/contexts/SignupContext";
import { ServiceType } from "@/lib/types";
 // Back-destination: last completed service setup step
function prevStep(roles: string[]): string { if (roles.includes("host")) return "/signup/hosting"; if (roles.includes("walker")) return "/signup/walking"; return "/signup/care-preferences";
} // Forward-destination: pet step (owners) or success
function nextStep(roles: string[]): string { if (roles.includes("owner")) return "/signup/pet"; return "/signup/success";
} type ServiceConfig = { type: ServiceType; label: string; unit: string; hint: string; marketRange: string; Icon: typeof PersonSimpleWalk;
}; const SERVICE_CONFIGS: ServiceConfig[] = [ { type: "walk_checkin", label: "Walks & Check-ins", unit: "per visit", hint: "A single walk or drop-in visit. Owners compare this first.", marketRange: "Typical in Prague: 250–700 Kč", Icon: PersonSimpleWalk, }, { type: "inhome_sitting", label: "In-home Sitting", unit: "per night", hint: "You stay at the owner's home overnight.", marketRange: "Typical in Prague: 700–1,400 Kč", Icon: House, }, { type: "boarding", label: "Boarding", unit: "per night", hint: "The dog stays at your home.", marketRange: "Typical in Prague: 600–1,200 Kč", Icon: PawPrint, },
]; function PriceInput({ config, value, onChange,
}: { config: ServiceConfig; value: number | null; onChange: (v: number | null) =>void;
}) { const { Icon, label, unit, hint, marketRange } = config; return (<div className="pricing-service-row"><div className="pricing-service-info"><div className="pricing-service-title"><Icon size={18} weight="duotone" className="pricing-service-icon" /><strong>{label}</strong></div><p className="pricing-service-hint">{hint}</p><p className="pricing-market-range">{marketRange}</p></div><div className="pricing-input-group"><div className="pricing-input-wrap"><input className="input pricing-input" type="number" min={150} max={2500} step={10} placeholder="e.g. 450" value={value ?? ""} onChange={(e) =>{ const raw = e.target.value; onChange(raw === "" ? null : Math.max(0, Number(raw))); }} /><span className="pricing-input-unit">Kč</span></div><span className="pricing-input-label">{unit}</span></div></div>);
} export default function SignupPricingPage() { const router = useRouter(); const { draft, updateDraft } = useSignupDraft(); // Only show services the provider actually offers const activeServices = SERVICE_CONFIGS.filter((cfg) =>{ if (cfg.type === "walk_checkin") return draft.roles.includes("walker"); if (cfg.type === "inhome_sitting") return draft.roles.includes("host"); if (cfg.type === "boarding") return draft.roles.includes("host"); return false; }); // Must set a price for each active service to continue const canContinue = activeServices.every( (cfg) =>draft.prices[cfg.type] !== null && (draft.prices[cfg.type] ?? 0) >0, ); const setPrice = (type: ServiceType, value: number | null) =>{ updateDraft({ prices: { ...draft.prices, [type]: value } }); }; return (<main className="page-shell"><div className="form-shell"><FormHeader title="Set Your Rates" subtitle="Set a starting price for each service. You can update these anytime from your profile." /><section className="form-body"><div className="form-row"><div className="form-col"><p className="form-section-label">Your Pricing</p><p style={{ fontSize: 14, color: "var(--text-tertiary)", lineHeight: "20px", marginTop: 8, }} >This is the minimum owners will see on your listing. You can always adjust or add service tiers later.</p></div><div className="form-col"><div className="pricing-services-list">{activeServices.map((cfg) =>(<PriceInput key={cfg.type} config={cfg} value={draft.prices[cfg.type]} onChange={(v) =>setPrice(cfg.type, v)} />))}</div></div></div></section><FormFooter onBack={() =>router.push(prevStep(draft.roles))} onContinue={() =>router.push(nextStep(draft.roles))} disableContinue={!canContinue} /></div></main>);
}
