import { ExploreFilters, ProviderCard, SignupDraft } from "@/lib/types";
import { FILTER_RATE_MAX_KC, FILTER_RATE_MIN_KC } from "@/lib/pricing";

export const defaultSignupDraft: SignupDraft = {
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  confirmPassword: "",
  roles: [],
  bio: "",
  location: "",
  publicProfile: false,
  pet: {
    name: "",
    breed: "",
    size: "",
    age: "",
    temperament: "",
    goodWithDogs: false,
    goodWithKids: false,
    healthNotes: "",
  },
  // Dogs you can care for
  dogSizes: [],
  dogAges: [],
  dogTemperamentsExcluded: [],
  dogSpecialNotes: "",
  dogsCanCareFor: [],
  // Walking service setup
  walkingRadius: 5,
  walkingDays: [],
  walkingTimes: [],
  // Hosting service setup
  hostDays: [],
  hostTimes: [],
  homeType: "",
  outdoorSpace: "",
  dogStayArea: "",
  // Pricing — set in /signup/pricing
  prices: {
    walk_checkin: null,
    inhome_sitting: null,
    boarding: null,
  },
  acceptTos: false,
  acceptPrivacy: false,
};

export const defaultExploreFilters: ExploreFilters = {
  service: null,
  address: "",
  dateRange: { start: null, end: null },
  startDate: null,
  times: [],
  minRate: FILTER_RATE_MIN_KC,
  maxRate: FILTER_RATE_MAX_KC,
  pets: ["Spot", "Goldie"],
};

export const dogsCareOptions = [
  "Small dogs (under 10kg)",
  "Medium dogs (10kg - 25kg)",
  "Large dogs (25kg+)",
  "Puppies",
  "Senior dogs",
  "High-energy breeds",
];

export const providers: ProviderCard[] = [
  {
    id: "olga-m",
    name: "Olga M.",
    district: "Prague 5",
    neighborhood: "Smichov",
    rating: 4.8,
    reviewCount: 12,
    priceFrom: 390,
    priceUnit: "per_walk",
    blurb: "Clean, fun & safe home for your pup",
    avatarUrl:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    services: ["walk_checkin", "inhome_sitting"],
    availableTimes: ["6-11", "11-15"],
    distanceKm: 0.8,
    neighbourhoodMatch: true,
    mutualConnections: 2,
    lat: 50.0757,
    lng: 14.402,
  },
  {
    id: "nikola-r",
    name: "Nikola R.",
    district: "Prague 2",
    neighborhood: "Vinohrady",
    rating: 4.9,
    reviewCount: 20,
    priceFrom: 470,
    priceUnit: "per_walk",
    blurb: "Structured walks and calm routines",
    avatarUrl:
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=200&q=80",
    services: ["walk_checkin", "boarding"],
    availableTimes: ["11-15", "15-22"],
    distanceKm: 2.3,
    neighbourhoodMatch: false,
    mutualConnections: 1,
    lat: 50.0748,
    lng: 14.4369,
  },
  {
    id: "jana-k",
    name: "Jana K.",
    district: "Prague 6",
    neighborhood: "Dejvice",
    rating: 4.7,
    reviewCount: 9,
    priceFrom: 330,
    priceUnit: "per_visit",
    blurb: "Patient care for shy and senior dogs",
    avatarUrl:
      "/images/generated/eva-profile.jpeg",
    services: ["walk_checkin", "inhome_sitting", "boarding"],
    availableTimes: ["6-11", "15-22"],
    distanceKm: 3.7,
    neighbourhoodMatch: false,
    mutualConnections: 0,
    lat: 50.101,
    lng: 14.3888,
  },
  {
    id: "tomas-b",
    name: "Tomáš B.",
    district: "Prague 3",
    neighborhood: "Žižkov",
    rating: 4.6,
    reviewCount: 7,
    priceFrom: 520,
    priceUnit: "per_walk",
    blurb: "Solo walks with a trainer's touch",
    avatarUrl:
      "/images/generated/shawn-profile.jpg",
    services: ["walk_checkin"],
    availableTimes: ["6-11", "15-22"],
    distanceKm: 1.5,
    neighbourhoodMatch: false,
    mutualConnections: 0,
    lat: 50.0834,
    lng: 14.451,
  },
  {
    id: "marketa-h",
    name: "Markéta H.",
    district: "Prague 1",
    neighborhood: "Staré Město",
    rating: 5.0,
    reviewCount: 34,
    priceFrom: 600,
    priceUnit: "per_walk",
    blurb: "Premium full-service care in the heart of Prague",
    avatarUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    services: ["walk_checkin", "inhome_sitting", "boarding"],
    availableTimes: ["11-15"],
    distanceKm: 3.2,
    neighbourhoodMatch: false,
    mutualConnections: 1,
    lat: 50.088,
    lng: 14.4189,
  },
  {
    id: "pavel-d",
    name: "Pavel D.",
    district: "Prague 8",
    neighborhood: "Karlín",
    rating: 4.5,
    reviewCount: 15,
    priceFrom: 440,
    priceUnit: "per_walk",
    blurb: "Family home, sociable dogs very welcome",
    avatarUrl:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80",
    services: ["walk_checkin", "boarding"],
    availableTimes: ["6-11", "11-15"],
    distanceKm: 4.1,
    neighbourhoodMatch: false,
    mutualConnections: 0,
    lat: 50.0944,
    lng: 14.45,
  },
  {
    id: "simona-v",
    name: "Simona V.",
    district: "Prague 4",
    neighborhood: "Nusle",
    rating: 4.8,
    reviewCount: 22,
    priceFrom: 350,
    priceUnit: "per_visit",
    blurb: "Calm, attentive home sitter — always available",
    avatarUrl:
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=200&q=80",
    services: ["inhome_sitting", "boarding"],
    availableTimes: ["11-15"],
    distanceKm: 2.0,
    neighbourhoodMatch: false,
    mutualConnections: 3,
    lat: 50.062,
    lng: 14.428,
  },
  {
    id: "martin-k",
    name: "Martin K.",
    district: "Prague 7",
    neighborhood: "Holešovice",
    rating: 4.7,
    reviewCount: 11,
    priceFrom: 480,
    priceUnit: "per_walk",
    blurb: "Active walks and reliable boarding by the river",
    avatarUrl:
      "/images/generated/martin-profile.jpeg",
    services: ["walk_checkin", "boarding"],
    availableTimes: ["6-11", "15-22"],
    distanceKm: 1.8,
    neighbourhoodMatch: false,
    mutualConnections: 1,
    lat: 50.1022,
    lng: 14.4342,
  },
  {
    id: "lenka-s",
    name: "Lenka S.",
    district: "Prague 10",
    neighborhood: "Vršovice",
    rating: 4.6,
    reviewCount: 8,
    priceFrom: 310,
    priceUnit: "per_visit",
    blurb: "Affordable care for all dogs — walks and overnight",
    avatarUrl:
      "/images/generated/jana-profile.jpeg",
    services: ["walk_checkin", "inhome_sitting", "boarding"],
    availableTimes: ["6-11", "11-15"],
    distanceKm: 2.9,
    neighbourhoodMatch: false,
    mutualConnections: 0,
    lat: 50.0697,
    lng: 14.4503,
  },
  {
    id: "petr-v",
    name: "Petr V.",
    district: "Prague 9",
    neighborhood: "Vysočany",
    rating: 4.9,
    reviewCount: 18,
    priceFrom: 720,
    priceUnit: "per_night",
    blurb: "Home away from home — sitting and boarding only",
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    services: ["inhome_sitting", "boarding"],
    availableTimes: ["6-11", "11-15", "15-22"],
    distanceKm: 5.2,
    neighbourhoodMatch: false,
    mutualConnections: 0,
    lat: 50.1094,
    lng: 14.4992,
  },
];
